module.exports = [
    { title: 'vue-基础', 
      collapsable: true,
      children:[
      '/vue-Basics/',
      '/vue-Basics/Basics1',
      '/vue-Basics/Basics2',
      '/vue-Basics/Basics3',
      '/vue-Basics/Basics4',
      '/vue-Basics/Basics5',
      '/vue-Basics/Basics6',
      '/vue-Basics/Basics7',
      '/vue-Basics/Basics8',
      '/vue-Basics/Basics9',
      '/vue-Basics/Basics10',
      '/vue-Basics/Basics11',
      '/vue-Basics/Basics12',
      '/vue-Basics/Basics13',
      '/vue-Basics/Basics14',
      '/vue-Basics/Basics15',
      '/vue-Basics/Basics16',
      ]
    },
    { title: 'vue-进阶', 
    collapsable: true,
    children:[
      '/vue-Basics/VBasics',
      '/vue-Basics/VBasics1',
      '/vue-Basics/VBasics2',
      '/vue-Basics/VBasics3',
      '/vue-Basics/VBasics4',
      '/vue-Basics/VBasics5',
      '/vue-Basics/VBasics6',
      '/vue-Basics/VBasics7',
      '/vue-Basics/VBasics8',
      '/vue-Basics/VBasics9',
      '/vue-Basics/VBasics10',
      '/vue-Basics/VBasics11',
      '/vue-Basics/VBasics12',
      '/vue-Basics/VBasics13',
      '/vue-Basics/VBasics14',
      '/vue-Basics/VBasics15',
      '/vue-Basics/VBasics16',
     ]
   },
   { title: 'vue-Webpack骨架', 
    collapsable: true,
    children:[
      '/vue-Basics/Vue-cli',
      '/vue-Basics/Vue-cli1',
      '/vue-Basics/Vue-cli2',
      '/vue-Basics/Vue-cli3',
      '/vue-Basics/Vue-cli4',
      '/vue-Basics/Vue-cli5',
      '/vue-Basics/Vue-cli6',
      '/vue-Basics/Vue-cli7',
      '/vue-Basics/Vue-cli8',
    ]
    },
    { title: 'vue-Webpack工程项目', 
    collapsable: true,
    children:[
      '/vue-Basics/Webpack',
      '/vue-Basics/Webpack1',
      '/vue-Basics/Webpack2',
      '/vue-Basics/Webpack3',
    ]
    }
]